- name: clone my dotfiles repo
  ansible.builtin.git:
    repo: "{{MY_REPO}}/dotfiles.git"
    dest: "~/dotfiles"
    depth: 1

- name: create symlink
  shell: cd {{ lookup('env', 'HOME')}}/dotfiles && stow -D -t ~ . && stow -t ~ .
